version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_package_id: $(APPVEYOR_PROJECT_NAME)
before_build:
- cmd: appveyor-retry nuget restore Source\%APPVEYOR_PROJECT_NAME%.sln
build:
  project: .\Source\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: normal
after_build:
- cmd: .\Build\NuGet\Package.cmd
- appveyor PushArtifact %NUGET_PACKAGE_ID%.%APPVEYOR_BUILD_VERSION%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: /0Z5Cw06AdhoTRWdDCY6lEf6mL6m2WzkA1KgiJnjwFfpHVgfdDMdqVHQPpnI1K6O
  skip_symbols: false
  artifact: $(NUGET_PACKAGE_ID).$(APPVEYOR_BUILD_VERSION).nupkg
  on:
    branch: master
    appveyor_repo_tag: true # Change to true for realeasing only git tag/releases.
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/56cdf2845db1a29559ea
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
